few_shots = [{'Question': 'Get me all employes with there depertment name ?',
  'SQLQuery': 'SELECT e.Emp_name, d.dep_name FROM employee_info e JOIN department_info d ON e.dep_id = d.dep_id ORDER BY e.Emp_name ',
  'SQLResult': 'The Result of the SQL Queary',
  'Answer': "[('Jasmine Patel', 'Dev'), ('Lucas Thompson', 'Analytics '), ('Maya Rodriguez', 'IT'), ('Ethan Carter', 'HR'), ('Ava Mitchell', 'Sales'), ('Dylan Williams', 'HR'), ('Sophia Nguyen', 'Dev'), ('Mason Wilson', 'IT'), ('Olivia Campbell', 'Analytics '), ('Liam Hernandez', 'Sales'), ('Isabella Cooper', 'Dev'), ('Noah Johnson', 'HR'), ('Emily Parker', 'IT'), ('Aiden Lewis', 'Analytics '), ('Mia Scott', 'Sales'), ('Alexander Stewart', 'HR'), ('Charlotte Adams', 'Dev'), ('Elijah Turner', 'IT'), ('Harper Ramirez', 'Sales'), ('Benjamin Martinez', 'Analytics ')]"},
 {'Question': 'total salary for dep HR ?',
  'SQLQuery': "select sum(A.annual_comp)  from emp_info.employee_info A join emp_info.department_info B on A.dep_id = B.dep_id where B.dep_name = 'HR' ",
  'SQLResult': 'The Result of the SQL Queary',
  'Answer': "2352" },
 {'Question': 'extract year from joining date',
  'SQLQuery': 'SELECT YEAR(`date_of_joining`) FROM employee_info ',
  'SQLResult': 'The Result of the SQL Queary',
  'Answer': '[2000, 2001, 2002, 2003]'},
 {'Question': 'What is the new salary of all employees ?',
  'SQLQuery': 'select A.annual_comp+ (A.annual_comp*(B.increment/100)) from emp_info.employee_info A join emp_info.increment B on A.Emp_id = B.Emp_id ',
  'SQLResult': 'The Result of the SQL Queary',
  'Answer': '(388.8, 961.2, 216.0, 675.15, 105.6, 677.7, 362.25, 1117.2, 198.0, 1050.3, 268.8, 717.6, 567.0, 880.8, 240.3, 639.45, 451.2, 866.25, 376.65, 680.4)'},
 {'Question': 'Who are the employee that have Good performance ?',
  'SQLQuery': "select A.Emp_name from emp_info.employee_info A join emp_info.increment B on A.Emp_id = B.Emp_id where B.Performace = 'Good' ",
  'SQLResult': 'The Result of the SQL Queary',
  'Answer': 'Jasmine Patel, Maya Rodriguez, Ava Mitchell, Mason Wilson, Olivia Campbell, Noah Johnson, Aiden Lewis, Charlotte Adams, Benjamin Martinez'},
  {'Question': 'give highest salary as per depertment ',
  'SQLQuery': "select B.dep_name, max(annual_comp) from emp_info.employee_info A join emp_info.department_info B on A.dep_id = B.dep_id group by B.dep_name ",
  'SQLResult': 'The Result of the SQL Queary',
  'Answer': "('Dev', '376,543'), ('Analytics ', '734,512'), ('IT', '931,245'), ('HR', '643,219'), ('Sales', '88,765')"},
  {'Question': 'Count of employees as per perfromance ?',
  'SQLQuery': "SELECT B.Performace , count(A.Emp_id) FROM emp_info.employee_info A  join emp_info.increment B on A.Emp_id = B.Emp_id group by B.Performace ;",
  'SQLResult': 'The Result of the SQL Queary',
  'Answer': "('Good', 9), ('Excellent', 6), ('Average', 5)"},
  {'Question': 'Get me all employee who have a rating of 3 ',
  'SQLQuery': "select A.Emp_name from emp_info.employee_info A join emp_info.increment B on A.Emp_id = B.Emp_id where B.Rating = 3;",
  'SQLResult': 'The Result of the SQL Queary',
  'Answer': "Ethan Carter,Sophia Nguyen,Isabella Cooper,Alexander Stewart,Elijah Turner"}]